apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  labels:
    app: gitops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:5678"
            - "-text=Hello from GitOps! Deployed and self-healed by ArgoCD. (Vivin, Shreyash, Tanmay - DevOps IA)"
          ports:
            - containerPort: 5678
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
